apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::153250763537:role/eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::153250763537:user/my-eks-user
      username: admin
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

