apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: retail-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bitnami/node:20   # public demo image
          ports:
            - containerPort: 8080

